WebUI/Models/BooksListViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class BooksListViewModel
    {
        public IEnumerable<Book> Books { get; set; }
        public PagingInfo PagingInfo { get; set; }
        public string CurrentGenre { get; set; }
    }
}

WebUI/Models/CartIndexViewModel.cs
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class CartIndexViewModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
    }
}

WebUI/Models/PagingInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebUI.Models
{
    public class PagingInfo
    {
        public int TotalItems { get; set; }     // Общее кол-во книг
        public int ItemsPerPage { get; set; }   // Кол-во книг на странице
        public int CurrentPage { get; set; }    // Номер текущей страницы
        public int TotalPages                   // Общее кол-во страниц
        {
            get { return (int)Math.Ceiling((decimal)TotalItems / ItemsPerPage); }
        }
    }
}

WebUI/Controllers/BooksController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class BooksController : Controller
    {
        private IBookRepository repository;

        public int pageSize = 4;
        
        public BooksController(IBookRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string genre, int page = 1)
        {
            BooksListViewModel model = new BooksListViewModel
            {
                Books = repository.Books
                .Where(b => genre == null || b.Genre == genre)
                .OrderBy(book => book.BookId)
                .Skip((page - 1) * pageSize)
                .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = genre == null ?
                        repository.Books.Count() :
                        repository.Books.Where(book => book.Genre == genre).Count()
                },
                CurrentGenre = genre
            };

            return View(model);
        }
    }
}

WebUI/Controllers/CartController.cs
using Domain.Abstract;
using Domain.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebUI.Models;

namespace WebUI.Controllers
{
    public class CartController : Controller
    {
        private IBookRepository repository;
        public CartController(IBookRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = GetCart(),
                ReturnUrl = returnUrl
            });
        }

        public Cart GetCart()
        {
            Cart cart = (Cart)Session["Cart"];
            if (cart == null)
            {
                cart = new Cart();
                Session["Cart"] = cart;
            }
            return cart;
        }

        public RedirectToRouteResult AddToCart(int bookId, string returnUrl)
        {
            Book book = repository.Books
                .FirstOrDefault(b => b.BookId == bookId);

            if (book != null)
            {
                GetCart().AddItem(book, 1);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToRouteResult RemoveFromCart(int bookId, string returnUrl)
        {
            Book book = repository.Books
                .FirstOrDefault(b => b.BookId == bookId);

            if (book != null)
            {
                GetCart().RemoveLine(book);
            }

            return RedirectToAction("Index", new { returnUrl });
        }
        
    }
}

WebUI/Controllers/NavController.cs
using Domain.Abstract;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebUI.Controllers
{
    public class NavController : Controller
    {
        private IBookRepository repository;

        public NavController(IBookRepository repo)
        {
            repository = repo;
        }

        public PartialViewResult Menu(string genre = null)
        {
            ViewBag.SelectedGenre = genre;

            IEnumerable<string> genres = repository.Books
                .Select(book => book.Genre)
                .Distinct()
                .OrderBy(x => x);

            return PartialView(genres);
        }
    }
}

WebUI/Views/Books/List.cshtml
@using WebUI.Models
@model BooksListViewModel
@using WebUI.HtmlHelpers

@{
    ViewBag.Title = "Книги";
}

@foreach (var book in Model.Books)
{
    @Html.Partial("_BookSummary", book)
}

<div class="btn-group pull-right">
    @Html.PageLinks(Model.PagingInfo, x => Url.Action("List", new {page = x, genre = Model.CurrentGenre}))
</div>

WebUI/Views/Cart/Index.cshtml
@model WebUI.Models.CartIndexViewModel

@{
    ViewBag.Title = "BooksStore - Ваша корзина";
}

<h2>@ViewBag.Title</h2>

<table class="table">
    <thead>
        <tr>
            <th>Количество</th>
            <th>Наименование</th>
            <th class="text-right">Цена</th>
            <th class="text-right">Сумма</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Book.Name - @line.Book.Author</td>
                <td class="text-right">@line.Book.Price.ToString("# руб")</td>
                <td class="text-right">@((line.Quantity * line.Book.Price).ToString("# руб"))</td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Итого:</td>
            <td class="text-right">
                @Model.Cart.ComputeTotalValue().ToString("# руб")
            </td>
        </tr>
    </tfoot>
</table>

<div class="text-center">
    <a class="btn btn-primary" href="@Model.ReturnUrl">Продолжить покупки</a>
</div>

WebUI/Views/Nav/Menu.cshtml
@model IEnumerable<string>

@Html.ActionLink("Домой", "List", "Books", null, new { @class = "btn btn-block btn-default btn-lg" })

@foreach (var link in Model)
{
    @Html.RouteLink(link, new
    {
        controller = "Books",
        action = "List",
        genre = link,
        page = 1
    }, new
    {
        @class = "btn btn-block btn-default btn-lg"
            + (link == ViewBag.SelectedGenre ? " btn-primary" : "")
    })
}

WebUI/Views/Shared/_BookSummary.cshtml
@model Domain.Entities.Book

<div class="well">
    <div class="row">
        <div class="col-xs-10">
            <h3>
                <strong>@Model.Name</strong>
            </h3>
            <h4>
                <strong>@Model.Author</strong>
            </h4>
        </div>
        <div class="col-xs-2">
            <h3>
                <strong id="price" class="pull-right label label-primary">
                    @Model.Price.ToString("# руб")
                </strong>
            </h3>
            @using (Html.BeginForm("AddToCart", "Cart"))
            {
                <div class="pull-right">
                    @Html.HiddenFor(x => x.BookId)
                    @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
                    <input type="submit" class="btn btn-success" value="Добавить в корзину" />
                </div>
            }
        </div>
    </div>
    <span class="lead">@Model.Description</span>
</div>
<hr />  

WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
  
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-brand" href="#">BookStore - книжный магазин</a>
    </div>

    <div class="row panel">
        <div id="genres" class="col-xs-3">
          @Html.Action("Menu", "Nav")
        </div>
        <div class="col-xs-8">
            @RenderBody()
        </div>
    </div>


</body>
</html>